### ISSUE TITLE
Issue for adding a new method in Canvas library and what to do to add a personal C++ library

### ISSUE THREAD

**Issue by GRicciardi00** [binji/wasm-clang#15]
I've tried to add a new method called mydebug() in "include/canvas.h" and "sysroot/include/canvas.h" and finally implemented it in shared.js (also in the const env defined into the class App) but the compiler doesn't recognize it.
Also I would like to know what I should do to add a personal library for C++ .

**Comment by binji** [comment]
What error do you get? Are you sure that it's loading the new header and not cached?

**Comment by GRicciardi00** [comment]
The compiler doesn't recognize the new function, the error given is: "use of undeclared identifier 'mydebug'
    mydebug();". I think that the problem is that I made the changes in the folders extracted from the sysroot.tar without having recompressed the archive again. I tried to do this but now the compiler doesn't recognize any library but I can't figure out why. Thank you for replying

**Comment by GRicciardi00** [comment]
So I solved the problem because I was tarring the files with MacOS and this and I solved it by creating the .tar on linux.
What should I do to add a personal library readable by the compiler using the "include" statement? (Ex. "include <aaa.h>"
