### ISSUE TITLE
libcanvas

### ISSUE THREAD

**Issue by spinicist** [binji/wasm-clang#2]
Hello,

Apologies, as I’m not sure this is the best place to ask this. Would you be willing to split your libcanvas out from this project and provide some very basic documentation?

I watched your talk months ago, and was seriously impressed by the whole thing. But in particular, it made me want to use C++ to draw some simple animations in my browser (the Doom fire effect was great!). I know next to nothing about WASM, but as far as I can tell from my research you have something fairly unique here. The only similar examples I can find use a full emscriptem and SDL approach, which particularly the latter is overkill for what I was thinking of, and your approach looked much cleaner in the final code.

Thanks in advance.

**Comment by binji** [comment]
Thanks for your interest! I don't know that if I have time to do this, but I agree it would be nice to have as an independent library. It would be even better to have the glue code automatically generated by something like the [WebAssembly interface-types proposal](http://github.com/webassembly/interface-types).

If you're interested in doing the work, I'd be happy to help you out with code reviews and direction, etc.!

**Comment by binji** [comment]
Just found this library which looks like a nice alternative: https://github.com/alextyner/wasm-canvas

**Comment by spinicist** [comment]
Hello,

I'm very time limited too (hence the delay in responding), so any progress I make will be slow! I was hoping to avoid emscriptem through a naïve desire to keep a minimal toolchain/set of dependencies. However, I think the pragmatic way forward is to use the library you have linked with emscriptem to learn the ropes, then in future attempt to do something without emscriptem. I'll let you know how I get on.

**Comment by spinicist** [comment]
Tidying up my old issues - thanks again for the talk!
