### ISSUE TITLE
Optimized clang.wasm

### ISSUE THREAD

**Issue by kripken** [binji/wasm-clang#4]
Looks like clang.wasm on the demo site wasn't optimized by wasm-opt. Attached is an optimized version, which is 13% smaller (34.10 MB to 29.77 MB)
[clangO.wasm.gz](https://github.com/binji/wasm-clang/files/4658177/clangO.wasm.gz)

**Comment by binji** [comment]
Nice, thanks! You may want to take a look at `lld` too.

**Comment by kripken** [comment]
Sure, attached.

lld is almost half the size, 34 MB to 19 MB.

[lldO.wasm.gz](https://github.com/binji/wasm-clang/files/4658459/lldO.wasm.gz)

**Comment by binji** [comment]
Updated here: https://github.com/binji/wasm-clang/commit/88838f3cf4a4e7dfae026fce4ef81c880f297808
